/**
 * Emits the dist artifacts that a plain-CSS consumer needs:
 *   fonts.css   — @font-face rules with unicode-range subsetting
 *   fonts.json  — the manifest, flattened for non-TS consumers
 *
 * The woff2 files themselves are *not* built here. They come from
 * `scripts/subset-fonts.py`, which needs Python + fontTools and so cannot run
 * on the CI runner; like `dist/` in the tokens package they are committed.
 * This script only reshapes the manifest that step leaves behind, which keeps
 * the CI freshness gate meaningful without putting Python in front of it.
 */
import { mkdir } from "node:fs/promises";
import { faces, fallback, families, upstream, type Face } from "./src/index.ts";

const OUT = new URL("./dist/", import.meta.url);

/** Wrap a long unicode-range list so the generated CSS stays readable. */
function wrapRanges(ranges: readonly string[], indent: string): string {
  const lines: string[] = [];
  let line = "";
  for (const r of ranges) {
    const next = line ? `${line}, ${r}` : r;
    if (next.length > 76) {
      lines.push(line + ",");
      line = r;
    } else {
      line = next;
    }
  }
  lines.push(line);
  return lines.join(`\n${indent}  `);
}

function fontFace(f: Face): string {
  return [
    "@font-face {",
    `  font-family: "${f.family}";`,
    `  font-style: ${f.style};`,
    // A variable range, so one file answers every weight token (400-700).
    `  font-weight: ${f.weight};`,
    "  font-display: swap;",
    `  src: url("./files/${f.file}") format("woff2");`,
    `  unicode-range: ${wrapRanges(f.unicodeRange, "  ")};`,
    "}",
  ].join("\n");
}

function buildCss(): string {
  // Only the split cuts belong in CSS. The `all` files exist for next/font,
  // which cannot express unicode-range; emitting them here would duplicate
  // every glyph and, because they collide on family/weight/style, the later
  // rule would quietly win.
  const split = faces.filter((f) => f.subset !== "all");
  const bytes = split.reduce((n, f) => n + f.bytes, 0);

  const header = [
    "/*",
    " * @tyandor/fonts — generated by packages/fonts/build.ts. Do not edit.",
    " *",
    ` * iA Writer Duo + Mono, variable (wght 400-700, SPCG 0-150), subsetted to`,
    ` * latin and latin-ext. ${split.length} files, ${bytes.toLocaleString()} bytes total; a reader who`,
    " * renders only basic latin fetches roughly half of that.",
    " *",
    ` * Upstream: ${upstream.repo} @ ${upstream.commit.slice(0, 8)}`,
    ` * Licence:  ${upstream.license} — see LICENSE-OFL.md, and PROVENANCE.md`,
    " *           for exactly what was modified.",
    " *",
    " * The family names below are the ones --ty-font-body and --ty-font-mono",
    " * already resolve to, so @tyandor/tokens needs no knowledge of this file.",
    " */",
    "",
  ].join("\n");

  const groups = families.map((family) => {
    const rules = split
      .filter((f) => f.family === family)
      .map(fontFace)
      .join("\n\n");
    return `/* ── ${family} ─────────────────────────────────────────── */\n\n${rules}`;
  });

  return `${header}\n${groups.join("\n\n")}\n`;
}

function buildJson(): string {
  return `${JSON.stringify({ upstream, families, fallback, faces }, null, 2)}\n`;
}

await mkdir(OUT, { recursive: true });
const outputs: Array<[string, string]> = [
  ["fonts.css", buildCss()],
  ["fonts.json", buildJson()],
];

for (const [file, contents] of outputs) {
  await Bun.write(new URL(file, OUT), contents);
  console.log(`  ${file.padEnd(20)} ${contents.length.toLocaleString()} bytes`);
}

const shipped = faces.reduce((n, f) => n + f.bytes, 0);
console.log(`\n${faces.length} cuts across ${families.length} families, ${shipped.toLocaleString()} bytes of woff2.`);
