/**
 * Emits the three dist artifacts (PLAN.md 1e):
 *   tokens.css          — :root / [data-theme] custom properties
 *   tailwind-preset.js   — Tailwind 3 preset (verified against 4's @theme too)
 *   tokens.json          — machine-readable bridge for nvim/terminal generators
 *
 * Plain TS on purpose. style-dictionary buys us nothing here that 200 lines
 * of string building doesn't, and it would put a build dependency in front of
 * the one package everything else depends on.
 */
import { mkdir } from "node:fs/promises";
import { accents, chartSeries, highlights, palette, type Variant } from "./src/color.ts";
import { roles, type RoleName } from "./src/themes.ts";
import { spacing, sizes, spacingOrder } from "./src/spacing.ts";
import { breakpoints, grid } from "./src/grid.ts";
import { duration, easing, shadow } from "./src/motion.ts";
import { fontFamily, fontWeight, typeScale } from "./src/type.ts";
import { rgbChannels } from "./src/contrast.ts";

const OUT = new URL("./dist/", import.meta.url);
const ROLE_NAMES = Object.keys(roles) as RoleName[];

const isHex = (v: string): boolean => /^#[0-9a-fA-F]{3,8}$/.test(v.trim());

/** Colour custom properties for one variant. Each hex also gets a `-rgb` twin. */
function colorVars(variant: Variant, indent = "  "): string {
  const lines: string[] = [];
  lines.push(`${indent}color-scheme: ${variant === "mcrn" ? "dark" : "light"};`);

  for (const name of ROLE_NAMES) {
    const value = roles[name].value[variant];
    lines.push(`${indent}--ty-${name}: ${value};`);
    // Channel twin so Tailwind opacity modifiers (bg-layer-01/50) work.
    if (isHex(value)) lines.push(`${indent}--ty-${name}-rgb: ${rgbChannels(value)};`);
  }

  lines.push("");
  lines.push(`${indent}/* Primitive accents — expressive use only (charts, syntax, labels). */`);
  for (const [key, a] of Object.entries(accents)) {
    lines.push(`${indent}--ty-accent-${key}: ${a[variant]};`);
    lines.push(`${indent}--ty-accent-${key}-rgb: ${rgbChannels(a[variant])};`);
  }
  for (const [key, h] of Object.entries(highlights)) {
    lines.push(`${indent}--ty-highlight-${key}: ${h[variant]};`);
  }

  lines.push("");
  lines.push(`${indent}/* Chart series, pre-ordered for hue separation. */`);
  chartSeries.forEach((name, i) => {
    lines.push(`${indent}--ty-chart-${String(i + 1).padStart(2, "0")}: ${accents[name][variant]};`);
  });

  lines.push("");
  for (const [key, s] of Object.entries(shadow)) {
    lines.push(`${indent}--ty-shadow-${key}: ${s[variant]};`);
  }

  return lines.join("\n");
}

/** Theme-invariant tokens: spacing, type, motion, grid. */
function staticVars(indent = "  "): string {
  const l: string[] = [];
  l.push(`${indent}/* Spacing — Carbon scale */`);
  for (const k of spacingOrder) l.push(`${indent}--ty-spacing-${k}: ${spacing[k]};`);
  for (const [k, v] of Object.entries(sizes)) l.push(`${indent}--ty-size-${k}: ${v};`);

  l.push("", `${indent}/* Typography */`);
  for (const [k, v] of Object.entries(fontFamily)) l.push(`${indent}--ty-font-${k}: ${v};`);
  for (const [k, v] of Object.entries(fontWeight)) l.push(`${indent}--ty-weight-${k}: ${v};`);
  for (const [k, t] of Object.entries(typeScale)) {
    l.push(`${indent}--ty-${k}-size: ${t.size};`);
    l.push(`${indent}--ty-${k}-line-height: ${t.lineHeight};`);
    l.push(`${indent}--ty-${k}-weight: ${t.weight};`);
    l.push(`${indent}--ty-${k}-letter-spacing: ${t.letterSpacing};`);
  }

  l.push("", `${indent}/* Motion */`);
  for (const [k, v] of Object.entries(duration)) l.push(`${indent}--ty-duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(easing)) l.push(`${indent}--ty-easing-${k}: ${v};`);

  l.push("", `${indent}/* Grid */`);
  for (const [k, v] of Object.entries(breakpoints)) l.push(`${indent}--ty-breakpoint-${k}: ${v};`);
  l.push(`${indent}--ty-grid-columns: ${grid.columns};`);
  l.push(`${indent}--ty-grid-mini-unit: ${grid.miniUnit};`);
  l.push(`${indent}--ty-grid-gutter: ${grid.gutter};`);
  l.push(`${indent}--ty-measure: ${grid.measure};`);

  return l.join("\n");
}

function buildCss(): string {
  return `/**
 * @tyandor/tokens — generated by packages/tokens/build.ts. Do not edit.
 *
 * MCRN (dark) is the default theme. Earth (light) applies when the visitor
 * has no explicit preference and their system asks for light, or whenever
 * [data-theme="earth"] is set. An explicit data-theme always wins: the
 * media-query block is scoped to :root:not([data-theme]), so it simply does
 * not match once a choice has been made.
 */

:root {
${colorVars("mcrn")}

${staticVars()}
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
${colorVars("earth", "    ")}
  }
}

[data-theme="earth"],
.ty-theme-earth {
${colorVars("earth")}
}

[data-theme="mcrn"],
.ty-theme-mcrn {
${colorVars("mcrn")}
}

/* ── Base utilities ───────────────────────────────────────────────── */

.ty-grid {
  display: grid;
  grid-template-columns: repeat(var(--ty-grid-columns), minmax(0, 1fr));
  gap: var(--ty-grid-gutter);
}

.ty-measure {
  max-width: var(--ty-measure);
}
`;
}

function buildPreset(): string {
  // rgb(var(--x-rgb) / <alpha-value>) keeps Tailwind opacity modifiers working.
  const color = (name: string): string => `rgb(var(--ty-${name}-rgb) / <alpha-value>)`;

  const colors: Record<string, unknown> = {};
  for (const name of ROLE_NAMES) {
    colors[name] = roles[name].kind === "scrim" ? `var(--ty-${name})` : color(name);
  }
  colors["accent"] = Object.fromEntries(Object.keys(accents).map((k) => [k, color(`accent-${k}`)]));
  colors["chart"] = Object.fromEntries(
    chartSeries.map((_, i) => {
      const n = String(i + 1).padStart(2, "0");
      return [n, `var(--ty-chart-${n})`];
    }),
  );

  const fontSize = Object.fromEntries(
    Object.entries(typeScale).map(([k, t]) => [
      k,
      [t.size, { lineHeight: t.lineHeight, letterSpacing: t.letterSpacing, fontWeight: t.weight }],
    ]),
  );

  const preset = {
    theme: {
      extend: {
        colors,
        spacing: Object.fromEntries(spacingOrder.map((k) => [k, spacing[k]])),
        screens: Object.fromEntries(Object.entries(breakpoints).map(([k, v]) => [k, v])),
        fontFamily: {
          body: ["var(--ty-font-body)"],
          mono: ["var(--ty-font-mono)"],
          prose: ["var(--ty-font-prose)"],
        },
        fontSize,
        fontWeight: Object.fromEntries(Object.entries(fontWeight).map(([k, v]) => [k, v])),
        height: sizes,
        minHeight: sizes,
        maxWidth: { measure: "var(--ty-measure)" },
        boxShadow: Object.fromEntries(Object.keys(shadow).map((k) => [k, `var(--ty-shadow-${k})`])),
        transitionDuration: Object.fromEntries(
          Object.keys(duration).map((k) => [k, `var(--ty-duration-${k})`]),
        ),
        transitionTimingFunction: Object.fromEntries(
          Object.keys(easing).map((k) => [k, `var(--ty-easing-${k})`]),
        ),
      },
    },
  };

  return `/**
 * @tyandor/tokens Tailwind preset — generated by packages/tokens/build.ts.
 * Do not edit.
 *
 * Requires tokens.css to be loaded: every value here resolves to a --ty-*
 * custom property, so the same class names produce both themes with no
 * Tailwind-level dark: variants at all.
 *
 * Tailwind 3:  presets: [require('@tyandor/tokens/tailwind-preset')]
 * Tailwind 4:  import the CSS and map with @theme; this file still works
 *              via @config for projects mid-migration.
 */
module.exports = ${JSON.stringify(preset, null, 2)};
`;
}

function buildJson(): string {
  const resolved = (variant: Variant) =>
    Object.fromEntries(ROLE_NAMES.map((n) => [n, roles[n].value[variant]]));

  return JSON.stringify(
    {
      $schema: "https://tyandor.com/schemas/tokens-1.json",
      name: "@tyandor/tokens",
      description:
        "Carbon's token taxonomy, the Expanse palette's values. Canonical machine-readable source for downstream theme generators (terminal, nvim).",
      variants: ["mcrn", "earth"],
      palette,
      chartSeries,
      roles: {
        meta: Object.fromEntries(
          ROLE_NAMES.map((n) => [n, { kind: roles[n].kind, desc: roles[n].desc }]),
        ),
        mcrn: resolved("mcrn"),
        earth: resolved("earth"),
      },
      spacing: Object.fromEntries(spacingOrder.map((k) => [k, spacing[k]])),
      sizes,
      breakpoints,
      grid,
      type: { fontFamily, fontWeight, scale: typeScale },
      motion: { duration, easing },
      shadow,
    },
    null,
    2,
  ) + "\n";
}

await mkdir(OUT, { recursive: true });
const outputs: Array<[string, string]> = [
  ["tokens.css", buildCss()],
  ["tailwind-preset.js", buildPreset()],
  ["tokens.json", buildJson()],
];

for (const [file, contents] of outputs) {
  await Bun.write(new URL(file, OUT), contents);
  console.log(`  ${file.padEnd(20)} ${contents.length.toLocaleString()} bytes`);
}
console.log(`\n${ROLE_NAMES.length} role tokens x 2 themes built.`);
