/**
 * Emits dist/ui.css.
 *
 * The build exists for two reasons, neither of them "compile CSS":
 *
 *   1. The twelve type-scale classes are generated from @tyandor/tokens, so
 *      adding a role to typeScale gives you .ty-type-<role> for free and
 *      there is no second list to keep in sync.
 *   2. Three gates run over the result. Together they turn the design
 *      system's principles from documentation into build failures:
 *        - no raw colour values          (Principle 1: tokens are the product)
 *        - no shadowing of tokens.css    (the package may not redefine the contract)
 *        - no reference to a token that does not exist (typos render nothing,
 *          silently, and only in one theme if you are unlucky)
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { typeScale, type TypeToken } from "@tyandor/tokens";

const STYLES = new URL("./src/styles/", import.meta.url);
const OUT = new URL("./dist/", import.meta.url);
const TOKENS_CSS = new URL("../tokens/dist/tokens.css", import.meta.url);

/**
 * Custom properties components set inline rather than tokens.css defining.
 * Every one is read with a var() fallback so the class still renders
 * standalone; listing them here is what lets the "unknown token" gate stay
 * strict about everything else.
 */
const COMPONENT_VARS = new Set([
  "--ty-stack-gap",
  "--ty-grid-layout-gap",
  "--ty-grid-layout-columns",
  "--ty-grid-layout-min",
  "--ty-container-max",
]);

/** Type-scale roles set in Mono; everything else takes the body stack. */
const isMono = (token: string): boolean => token.startsWith("code-");

function typeScaleCss(): string {
  const out: string[] = [
    "/* ── Type scale ───────────────────────────────────────────────────── */",
    "/* GENERATED from @tyandor/tokens typeScale by build.ts — do not edit. */",
    "",
  ];
  for (const token of Object.keys(typeScale) as TypeToken[]) {
    out.push(`.ty-type-${token} {`);
    out.push(`  font-family: var(${isMono(token) ? "--ty-font-mono" : "--ty-font-body"});`);
    out.push(`  font-size: var(--ty-${token}-size);`);
    out.push(`  line-height: var(--ty-${token}-line-height);`);
    out.push(`  font-weight: var(--ty-${token}-weight);`);
    out.push(`  letter-spacing: var(--ty-${token}-letter-spacing);`);
    out.push(`}`);
  }
  return out.join("\n");
}

/** Strips comments and string literals so gates never match on prose. */
function strip(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, "").replace(/"[^"]*"/g, '""');
}

/** Every `--ty-…` a stylesheet DEFINES (declaration position). */
function definedVars(css: string): Set<string> {
  return new Set(strip(css).match(/(--ty-[a-z0-9-]+)\s*:/gi)?.map((m) => m.split(":")[0]!.trim()) ?? []);
}

/** Every `--ty-…` a stylesheet READS (inside var()). */
function referencedVars(css: string): Set<string> {
  return new Set(
    [...strip(css).matchAll(/var\(\s*(--ty-[a-z0-9-]+)/gi)].map((m) => m[1]!),
  );
}

/** Class selectors a stylesheet defines, e.g. `.ty-grid` -> "ty-grid". */
function definedClasses(css: string): Set<string> {
  return new Set([...strip(css).matchAll(/\.(ty-[a-z0-9_-]+)/gi)].map((m) => m[1]!));
}

const fail = (msg: string, detail: readonly string[]): never => {
  console.error(`\n@tyandor/ui build failed: ${msg}\n`);
  for (const d of detail) console.error(`  ${d}`);
  console.error("");
  process.exit(1);
};

// ── Assemble ────────────────────────────────────────────────────────────

const partials = (await readdir(STYLES)).filter((f) => f.endsWith(".css")).sort();
const chunks: string[] = [];

for (const file of partials) {
  const body = (await readFile(new URL(file, STYLES), "utf8")).trimEnd();
  // The generated scale belongs with the hand-written typography rules.
  if (file === "02-type.css") chunks.push(typeScaleCss(), "");
  chunks.push(body, "");
}

const css = [
  "/*",
  " * @tyandor/ui — component styles.",
  " *",
  " * GENERATED by packages/ui/build.ts from src/styles/*.css. Do not edit.",
  " *",
  " * Load AFTER @tyandor/tokens/tokens.css: every value here resolves through",
  " * a --ty-* custom property, and without the token layer these rules render",
  " * as unset. Nothing in this file is a literal colour.",
  " */",
  "",
  ...chunks,
].join("\n");

// ── Gate 1: no raw colour values ────────────────────────────────────────

const rawColors = [
  ...strip(css).matchAll(/#[0-9a-f]{3,8}\b|\b(?:rgb|hsl)a?\(\s*[\d.]/gi),
].map((m) => m[0]);

if (rawColors.length > 0) {
  fail("raw colour values found — components must resolve colour through --ty-* tokens", [
    ...new Set(rawColors),
  ]);
}

// ── Gate 2: no shadowing of the token layer ─────────────────────────────

/*
 * Ordering is guaranteed by the workspace dependency on @tyandor/tokens —
 * `bun run --filter './packages/*' build` walks the graph, so tokens/dist
 * exists by the time this runs. Stated explicitly because the coupling is
 * otherwise invisible, and an ENOENT stack trace would not explain it.
 */
const tokensCss = await readFile(TOKENS_CSS, "utf8").catch(() => {
  fail("@tyandor/tokens has not been built", [
    "dist/tokens.css is missing, so the shadowing and unknown-token gates",
    "cannot run. Build the tokens package first:",
    "",
    "  bun run --filter './packages/*' build",
  ]);
  return "";
});
const shadowed = [...definedClasses(css)].filter((c) => definedClasses(tokensCss).has(c));

if (shadowed.length > 0) {
  fail("these classes are already defined by @tyandor/tokens/tokens.css", [
    ...shadowed.map((c) => `.${c}`),
    "",
    "Redefining them changes behaviour for vanilla-CSS consumers who never",
    "installed @tyandor/ui. Rename, or use the tokens.css class as-is.",
  ]);
}

// ── Gate 3: every referenced token exists ───────────────────────────────

const known = definedVars(tokensCss).union(definedVars(css)).union(COMPONENT_VARS);
const unknown = [...referencedVars(css)].filter((v) => !known.has(v));

if (unknown.length > 0) {
  fail("these custom properties are referenced but never defined", [
    ...unknown,
    "",
    "Either the name is a typo, or the token needs adding to @tyandor/tokens.",
    "A var() that resolves to nothing fails silently at runtime.",
  ]);
}

// ── Emit ────────────────────────────────────────────────────────────────

await mkdir(OUT, { recursive: true });
await writeFile(new URL("ui.css", OUT), css);

const classCount = definedClasses(css).size;
console.log(
  `@tyandor/ui: dist/ui.css — ${classCount} classes, ` +
    `${referencedVars(css).size} tokens referenced, ${partials.length} partials, ` +
    `${(css.length / 1024).toFixed(1)} kB`,
);
